//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public int STUDENT_ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public Nullable<int> STUDENT_FEES { get; set; }
        public string STUDENT_CITY { get; set; }
    }
}
